version = 0.1
[default.deploy.parameters]
stack_name = "spring-boot-serveless"
resolve_s3 = true
s3_prefix = "spring-boot-serveless"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
